"""empty message

Revision ID: 4798e0efd860
Revises: c38daf2b928a
Create Date: 2021-10-19 14:09:28.473548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4798e0efd860'
down_revision = 'c38daf2b928a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subreddits', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subreddits', type_='foreignkey')
    op.drop_column('subreddits', 'owner_id')
    # ### end Alembic commands ###
